title: My awesome title
author: Bircan GÃ¼rmen
email: bircan.guermen@adesso.de
description: > # this means to ignore newlines until "baseurl:"
  Don't read this, please.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  adessoBGuermen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
